### PR TITLE
Update vfb_plugin_exporter.cpp

### PR DESCRIPTION
**Pull request by haikalle**
This change make fog gizmo to work. It quick hack because I'm not quite sure does this change break other things.

### CODE REVIEW

**Comment by poseidon4o** [comment]
Hey, thank you for the effort to fix this! Unfortunately this change will break some unreleased changes we have.

I have pushed a fix for the fog gizmo with 7d891b15ddf525b2138649612f3c4f98c1183e38 

Please test if you can if the change resolves all issues with the fog gizmo and if not write back!

**Comment by haikalle** [comment]
Thank you. Fog gizmo works right now but if I don't use "fog gizmo" node, only Fog node, it dosen't work. There is no fog.

**Comment by poseidon4o** [comment]
Okay, now EnvironmentFog will render without gizmo and cover the whole scene.

**Comment by haikalle** [comment]
Wau! Thanks so much. One happy V-ray user right now :)

ma 4. helmik. 2019 klo 15.12 Lyubomir (notifications@github.com) kirjoitti:

**Pull request closed without merging**
